### ISSUE TITLE
外地人缺什么教学条件？

### ISSUE THREAD

**Issue by ghost** [Kahaani/gatian#1]
请问除了生活环境<ins>和语法</ins>之外，外地人要掌握读音还得会些什么呢？
我的基本目标就是能通过此输入法方便查询比较各方言的发音异同。

**Comment by kahaani** [comment]
感谢你的关注。

这份教程的目标是帮助潮汕人**认识母语的音系**。比如在介绍塞音声母的时候，教程中举了下面的例子，这里假设读者已经知道这三个字的读音，可以通过对比来体会三类塞音的差别。

```
普：[pʰou]²
补：[pou]²
亩：[bou]²
```

正如你所说，外地人要**学潮汕话**，除了语音，还有词汇和语法，要有大量的输入和输出——这超出了本教程的内容。反而是，有很多人在不具备语言学知识的情况下，通过电视电影、流行歌曲、日常会话学会了一门方言。

如果不会说潮汕话，但是具备语音学基础，希望通过这份教程来**简单了解一下潮汕话的音系**，我觉得是可行的。但是具体的音值，需要参考网上的音频资料。

至于你提到的方音比较，应该有比输入法更好的资料，比如《汉语方音字汇》、《汉语方言地图集》、《广州话、客家话、潮汕话与普通话对照词典》，还有**学术界**的一些方言调查资料和方言数据库。

不管怎样，如果你愿意成为这份教程的读者，我会很乐意听到你分享读后的感受或建议。:smile:

**Comment by ghost** [comment]
感谢说明。:-)
