### ISSUE TITLE
请问有无PDF版本？

### ISSUE THREAD

**Issue by ztl8702** [Kahaani/gatian#2]
最近很多墙内网页反映 Host 在 Github.io 的版本无法范围。可否生成一个PDF版本供下载？

**Comment by kahaani** [comment]
谢谢你的意见。

试过用 GitBook 生成 PDF，觉得字体、排版不佳，可能要费时间调参数。

对于离线阅读的需求，我把 HTML 打包放在网盘上（[链接](http://pan.baidu.com/s/1kUJt5JL#path=%252F%25E6%25BD%25AE%25E8%25AF%25AD%25E6%258B%25BC%25E9%259F%25B3%25E8%25BE%2593%25E5%2585%25A5%25E6%25B3%2595%252F%25E6%25BD%25AE%25E8%25AF%25AD%25E6%258B%25BC%25E9%259F%25B3%25E6%2595%2599%25E7%25A8%258B%25EF%25BC%2588%25E7%25A6%25BB%25E7%25BA%25BF%25E9%2598%2585%25E8%25AF%25BB%25E5%258C%2585%25EF%25BC%2589)），下载后解压，浏览`index.html`即可。

对于 GitHub 在墙内的问题，可以同时托管在国内的网站，比如 GitCafe（现在是 Coding.net），将国外的访问指向 GitHub，国内的访问指向 GitCafe。具体做法可以参考[这篇文章](http://fzheng.me/2015/07/25/tuoguanboke/)。

**Comment by ztl8702** [comment]
多谢。
