### ISSUE TITLE
Weasel has updated to 0.10.0

### ISSUE THREAD

**Issue by sgalal** [Kahaani/gatian#3]
[Weasel 0.10.0](https://github.com/rime/weasel/commit/0cf7f4223e8fd067dcaa6e300bc20b54aeceb47d) has been released 3 days ago, and has fixed the compatibility problems on Win 10 platform.

So the related content like the latest version and compatibility problems in `appendix2` should be updated.

P.S. In the tutorial, `小狼毫(TSF)`  should be `小狼毫（TSF）` , just like what it is in Weasel program.

**Comment by kahaani** [comment]
Cool! Thank you for the notice. I will update the tutorial.

**Comment by kahaani** [comment]
Updated.
