### ISSUE TITLE
在那个“潮语拼音教程”中的第一章第三节中的那个语料一中，“甲”的正字好像是亻+合

### ISSUE THREAD

**Issue by hoist1999** [Kahaani/gatian#4]
转发了一个用户的反馈信息给你哦。

**Comment by kahaani** [comment]
谢谢热心反馈。

那两段话引用自李永明先生的《潮州方言》（1959），有些地方用了同音字而不是本字。既然是引用就尊重原文啦。

「佮」字在Unicode里有收录。也有认为这个词的本字就是「合」，不必加单人旁。

**Comment by kahaani** [comment]
发现这条反馈是从母语网留言板转载过来的。谢谢热心的诸位。
